### ISSUE TITLE
Support for  Wemo Light Switch

### ISSUE THREAD

**Issue by rudders** [timonreinhard/wemo-client#15]
Hey tim - any reason not to support the Wemo Light Switch? 

```javascript
Wemo.DEVICE_TYPE = {
  Bridge: 'urn:Belkin:device:bridge:1',
  Switch: 'urn:Belkin:device:controllee:1',
  Motion: 'urn:Belkin:device:sensor:1',
  Maker: 'urn:Belkin:device:Maker:1',
  Insight: 'urn:Belkin:device:insight:1',
  LightSwitch: 'urn:Belkin:device:lightswitch:1' // added???
};
```

**Comment by timonreinhard** [comment]
The only reason behind is that I don't have one, hence I have no idea what service and event types it supports. You're very welcome to add this device. Just make sure to include some tests and fixtures as I can't test the real hardware.

**Comment by rudders** [comment]
Same problem for me when it comes to testing. I've got someone testing on/off functionality for now and might take a close look sometime. Cheers
