### ISSUE TITLE
Add support for wemo COFFEE MAKER?

### ISSUE THREAD

**Issue by tekuonline** [timonreinhard/wemo-client#25]
Is it possible that we can add support for coffee maker? I did some research and found that the port for coffeemaker is 49154 and i was able to get eventservice.xml which I am attaching it here. 

https://www.dropbox.com/s/j0yq839ffx0dtrs/eventservice.xml?dl=0

Also, i think its same for the Crockpot too. 

Thanks..

**Comment by timonreinhard** [comment]
Sure. You would need to add the corresponding [Wemo.DEVICE_TYPE](https://github.com/timonreinhard/wemo-client/blob/v0.6.3/index.js#L14) and implement the `CrockpotState` (similar to `BinaryState`).

**Comment by timonreinhard** [comment]
Closing due to lack of feedback.
