### ISSUE TITLE
Subscription error: ECONNRESET throwing unhandled

### ISSUE THREAD

**Issue by dircm** [timonreinhard/wemo-client#32]
Getting unhandled error from events.js after installing 0.8.0::

Triggering when light turns on.

```
wemo-client Subscription error: ECONNRESET - Device: uuid:Lightswitch-1_0-221530K1301390, Service: urn:Belkin:service:basicevent:1 +26ms
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at TCP.onread (net.js:544:26)
pi@raspberrypi:~/HAP-NodeJS $ 
```

**Comment by timonreinhard** [comment]
You need to attach an error event listener to the client: `wemo.client(deviceInfo).on('error', function(err) { … })`

**Comment by nfarina** [comment]
Just got bitten by this - might be nice to include this in the README sample code!

**Comment by timonreinhard** [comment]
Thanks for your feedback. With 612cacf the README has been updated accordingly.
