### ISSUE TITLE
Wemo Device Found: null

### ISSUE THREAD

**Issue by christopheradorna** [timonreinhard/wemo-client#53]
Hi - I'm using the discover method:
```
	var Wemo = require('wemo-client');
	var wemo = new Wemo();
	wemo.discover(function(deviceInfo) {
	  console.log('Wemo Device Found: %j', deviceInfo);
	});
```
And get back "Wemo Device Found: null". I do know however that there is a Wemo device on my network as I can interact with it using the official Wemo Android app. Any help would be much appreciated. Thanks!

**Comment by timonreinhard** [comment]
There was a breaking change in release v0.13.0 that introduced an `err` first callback for the discover function (#51). So the signature changed to `function (err, deviceInfo)`.

**Comment by christopheradorna** [comment]
Thank you!!!

**Comment by totumhost** [comment]
Hi, Thanks for the amazing work. The above issue is also present in the "examples" in the npm version of the library. Had to do a "npm install git+https://github.com/timonreinhard/wemo-client.git" to get the working examples.
