### ISSUE TITLE
Question on next release

### ISSUE THREAD

**Issue by aguilucho2017** [timonreinhard/wemo-client#57]
Hi Timon

Thanks for all. One question, when is the next release going out? E.g. 0.14 ?

Thanks

**Comment by timonreinhard** [comment]
That's long overdue due, I plan to get it ready the next days.

**Comment by aguilucho2017** [comment]
Hi Timon!, sorry to be pushy about this, but, do you have any estimated time to release ? as the home bridge code depends on it to support the Wemo Dimmer. Thanks Much!
Martin.

**Comment by timonreinhard** [comment]
Thanks for the friendly reminder :-) v0.14.0 is out now.
